package Vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Ronnie Herrera
 */
public class Boleta extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Boleta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHoja = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdCarrito = new javax.swing.JTable();
        jLabelDetalleCompra = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtTotalFormaPago = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtTotal = new javax.swing.JTextPane();
        jLabelTotal = new javax.swing.JLabel();
        jLabel1FormaPago = new javax.swing.JLabel();
        jScrollPaneDireccion = new javax.swing.JScrollPane();
        txtTotal5 = new javax.swing.JTextPane();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelEstadoPedido = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtTotalEstadoPedido = new javax.swing.JTextPane();
        jPanelDatos = new javax.swing.JPanel();
        jLabelNombreCliente = new javax.swing.JLabel();
        jLabelDNI = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTextPanelDNI = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollNumero = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTotalCorreo = new javax.swing.JTextPane();
        jLabelNumeroPedido = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jPanelHoja.setBackground(new java.awt.Color(255, 255, 255));

        tblProdCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Codigo", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblProdCarrito);

        jLabelDetalleCompra.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelDetalleCompra.setText("Detale de Compra:");
        jLabelDetalleCompra.setMaximumSize(new java.awt.Dimension(40, 30));
        jLabelDetalleCompra.setMinimumSize(new java.awt.Dimension(40, 30));
        jLabelDetalleCompra.setPreferredSize(new java.awt.Dimension(40, 30));

        jScrollPane8.setViewportView(txtTotalFormaPago);

        jScrollPane5.setViewportView(txtTotal);

        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTotal.setText("Total:");

        jLabel1FormaPago.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1FormaPago.setText("Forma de Pago:");
        jLabel1FormaPago.setMaximumSize(new java.awt.Dimension(40, 30));
        jLabel1FormaPago.setMinimumSize(new java.awt.Dimension(40, 30));
        jLabel1FormaPago.setPreferredSize(new java.awt.Dimension(40, 30));

        jScrollPaneDireccion.setViewportView(txtTotal5);

        jLabelDireccion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelDireccion.setText("Direccion de Entrega");
        jLabelDireccion.setMaximumSize(new java.awt.Dimension(40, 30));
        jLabelDireccion.setMinimumSize(new java.awt.Dimension(40, 30));
        jLabelDireccion.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabelEstadoPedido.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelEstadoPedido.setText("Estado de Pedido:");
        jLabelEstadoPedido.setMaximumSize(new java.awt.Dimension(40, 30));
        jLabelEstadoPedido.setMinimumSize(new java.awt.Dimension(40, 30));
        jLabelEstadoPedido.setPreferredSize(new java.awt.Dimension(40, 30));

        jScrollPane6.setViewportView(txtTotalEstadoPedido);

        jPanelDatos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS:"));

        jLabelNombreCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelNombreCliente.setText("Nombre del cliente*");
        jLabelNombreCliente.setMaximumSize(new java.awt.Dimension(40, 30));
        jLabelNombreCliente.setMinimumSize(new java.awt.Dimension(40, 30));
        jLabelNombreCliente.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabelDNI.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelDNI.setText("DNI:");

        jLabelNumero.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelNumero.setText("Numero");

        jLabelCorreo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelCorreo.setText("Correo:");

        jScrollPane2.setViewportView(JTextPanelDNI);

        jScrollPane3.setViewportView(jScrollNumero);

        jScrollPane4.setViewportView(txtTotalCorreo);

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDNI)
                            .addComponent(jLabelNumero)
                            .addComponent(jLabelCorreo))
                        .addGap(68, 68, 68)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4)))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDNI)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumero)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCorreo)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelNumeroPedido.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelNumeroPedido.setText("Numero de Pedido:");
        jLabelNumeroPedido.setMaximumSize(new java.awt.Dimension(40, 30));
        jLabelNumeroPedido.setMinimumSize(new java.awt.Dimension(40, 30));
        jLabelNumeroPedido.setPreferredSize(new java.awt.Dimension(40, 30));

        javax.swing.GroupLayout jPanelHojaLayout = new javax.swing.GroupLayout(jPanelHoja);
        jPanelHoja.setLayout(jPanelHojaLayout);
        jPanelHojaLayout.setHorizontalGroup(
            jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHojaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHojaLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addComponent(jLabelTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(jPanelHojaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addComponent(jLabelDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneDireccion)
                            .addGroup(jPanelHojaLayout.createSequentialGroup()
                                .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1FormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                                        .addComponent(jLabelEstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(124, 124, 124))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHojaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanelHojaLayout.setVerticalGroup(
            jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHojaLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabelNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addComponent(jLabelEstadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1FormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabelDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTotal)))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jButtonBuscar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(0, 27, 72));
        jButtonBuscar.setText("Descargar");
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseClicked(evt);
            }
        });
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanelHoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelHoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseClicked
        /*ODO add your handling code here:
        String apellido = jTextApellido.getText();
        String nombre = jTextNombre.getText();
        String grado = jComboBox1.getSelectedItem().toString();

        List<Map<String, String>> alumnos = DatabaseUtils.buscarAlumnos(apellido, nombre, grado);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        alumnoIds.clear(); // Clear the list before adding new IDs

        for (Map<String, String> alumno : alumnos) {
            alumnoIds.add(alumno.get("id"));
            model.addRow(new Object[]{
                alumno.get("apellido"),
                alumno.get("nombre"),
                alumno.get("grado"),
                alumno.get("seccion")
            });
        }
        alumnos.clear();*/
    }//GEN-LAST:event_jButtonBuscarMouseClicked

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextPane JTextPanelDNI;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1FormaPago;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDetalleCompra;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelEstadoPedido;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelNumeroPedido;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelHoja;
    public javax.swing.JTextPane jScrollNumero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPaneDireccion;
    public javax.swing.JTable tblProdCarrito;
    public javax.swing.JTextPane txtTotal;
    public javax.swing.JTextPane txtTotal5;
    public javax.swing.JTextPane txtTotalCorreo;
    public javax.swing.JTextPane txtTotalEstadoPedido;
    public javax.swing.JTextPane txtTotalFormaPago;
    // End of variables declaration//GEN-END:variables
}
