package Vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Ronnie Herrera
 */
public class Boleta extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Boleta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHoja = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdPedido = new javax.swing.JTable();
        jLabelDetalleCompra = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtTotal = new javax.swing.JTextPane();
        jLabelTotal = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jLabelNombreCliente = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelNumeroPedido1 = new javax.swing.JLabel();
        jButtonDescargar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jPanelHoja.setBackground(new java.awt.Color(255, 255, 255));

        tblProdPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Codigo", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblProdPedido);

        jLabelDetalleCompra.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelDetalleCompra.setText("Detale de Compra:");
        jLabelDetalleCompra.setMaximumSize(new java.awt.Dimension(40, 30));
        jLabelDetalleCompra.setMinimumSize(new java.awt.Dimension(40, 30));
        jLabelDetalleCompra.setPreferredSize(new java.awt.Dimension(40, 30));

        jScrollPane5.setViewportView(txtTotal);

        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTotal.setText("Total:");

        jLabelDireccion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelDireccion.setText("Direccion de Entrega");
        jLabelDireccion.setMaximumSize(new java.awt.Dimension(40, 30));
        jLabelDireccion.setMinimumSize(new java.awt.Dimension(40, 30));
        jLabelDireccion.setPreferredSize(new java.awt.Dimension(40, 30));

        jPanelDatos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS:"));

        jLabelNombreCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelNombreCliente.setText("Nombre del cliente*");
        jLabelNombreCliente.setMaximumSize(new java.awt.Dimension(40, 30));
        jLabelNombreCliente.setMinimumSize(new java.awt.Dimension(40, 30));
        jLabelNombreCliente.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabelNumero.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelNumero.setText("Numero");

        jLabelCorreo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelCorreo.setText("Correo");

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNumero)
                            .addComponent(jLabelCorreo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNumero)
                .addGap(12, 12, 12)
                .addComponent(jLabelCorreo)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabelNumeroPedido1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelNumeroPedido1.setText("Direccion de Entrega:");
        jLabelNumeroPedido1.setMaximumSize(new java.awt.Dimension(40, 30));
        jLabelNumeroPedido1.setMinimumSize(new java.awt.Dimension(40, 30));
        jLabelNumeroPedido1.setPreferredSize(new java.awt.Dimension(40, 30));

        javax.swing.GroupLayout jPanelHojaLayout = new javax.swing.GroupLayout(jPanelHoja);
        jPanelHoja.setLayout(jPanelHojaLayout);
        jPanelHojaLayout.setHorizontalGroup(
            jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHojaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTotal)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanelHojaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelHojaLayout.createSequentialGroup()
                                .addComponent(jLabelDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanelHojaLayout.createSequentialGroup()
                        .addComponent(jLabelNumeroPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanelHojaLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHojaLayout.setVerticalGroup(
            jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHojaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabelNumeroPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabelDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotal))
                .addGap(1045, 1045, 1045))
        );

        jButtonDescargar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonDescargar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDescargar.setForeground(new java.awt.Color(0, 27, 72));
        jButtonDescargar.setText("Descargar");
        jButtonDescargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDescargarMouseClicked(evt);
            }
        });
        jButtonDescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDescargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDescargar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelHoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButtonDescargar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelHoja, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDescargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDescargarMouseClicked
        /*ODO add your handling code here:
        String apellido = jTextApellido.getText();
        String nombre = jTextNombre.getText();
        String grado = jComboBox1.getSelectedItem().toString();

        List<Map<String, String>> alumnos = DatabaseUtils.buscarAlumnos(apellido, nombre, grado);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        alumnoIds.clear(); // Clear the list before adding new IDs

        for (Map<String, String> alumno : alumnos) {
            alumnoIds.add(alumno.get("id"));
            model.addRow(new Object[]{
                alumno.get("apellido"),
                alumno.get("nombre"),
                alumno.get("grado"),
                alumno.get("seccion")
            });
        }
        alumnos.clear();*/
    }//GEN-LAST:event_jButtonDescargarMouseClicked

    private void jButtonDescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDescargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDescargarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonDescargar;
    public javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelDetalleCompra;
    public javax.swing.JLabel jLabelDireccion;
    public javax.swing.JLabel jLabelNombreCliente;
    public javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelNumeroPedido1;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelHoja;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTable tblProdPedido;
    public javax.swing.JTextPane txtTotal;
    // End of variables declaration//GEN-END:variables
}
