
package Vista;
import Conexión.Conexión;
import Modelo.ConexionLogin;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
/**
 *
 * @author MATHIAS
 */
public class Login extends javax.swing.JPanel {

    //private Principal principal;
    CardLayout cardLayout; //se tuvieron q colocar estos dos como atributo para poder pasarlos ccomo
    //parametro en el constructor ya que no hay controlador para hcerlo desde el main :D .L.
    Principal principal;
    Tienda tienda;
    public int ID;

    

    /**
     * Creates new form Login
     */
    public Login(CardLayout cardloLayout,Principal principal) {
        this.tienda = tienda;
        this.cardLayout = cardloLayout;
        this.principal = principal;
        //this.principal = principal;
        initComponents();
        initStyles();
        addRoundedPanel();
    }
    
    private void initStyles(){
        jTextFieldUsuario.putClientProperty( "JComponent.roundRect", true );
        jTextFieldPassword.putClientProperty( "JComponent.roundRect", true );
        jTextFieldUsuario.setColumns(15); // 15 columnas visibles
        jTextFieldPassword.setColumns(15);
        jButtonIngresar.putClientProperty( "JButton.buttonType", "roundRect" );
    }
    
    private void addRoundedPanel() {    
        RoundedPanel roundedPanel = new RoundedPanel(30); // Bordes redondeados con radio de 30
        roundedPanel.setBackground(Color.LIGHT_GRAY); // Fondo gris para el RoundedPanel
        roundedPanel.setPreferredSize(new java.awt.Dimension(760, 520)); // Tamaño preferido

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        roundedPanel.setLayout(layout);

        // Posiciona el jLabel1 (imagen) en el centro superior
        gbc.gridx = 0; 
        gbc.gridy = 0;
        gbc.gridwidth = 2; // Ocupa dos columnas para centrar
        gbc.anchor = java.awt.GridBagConstraints.CENTER;
        gbc.insets = new java.awt.Insets(10, 0, 20, 0); // Espacio alrededor de la imagen
        roundedPanel.add(jLabel1, gbc);

        // Agrega la etiqueta de usuario en la siguiente fila
        gbc.gridwidth = 1; // Restablece a una columna
        gbc.gridy = 1;
        gbc.gridx = 0;
        gbc.anchor = java.awt.GridBagConstraints.EAST;
        gbc.insets = new java.awt.Insets(10, 10, 10, 5); // Ajuste de espacio para alineación
        roundedPanel.add(jLabelUsuario, gbc);

        // Campo de texto de usuario al lado de la etiqueta
        gbc.gridx = 1;
        gbc.anchor = java.awt.GridBagConstraints.WEST;
        gbc.insets = new java.awt.Insets(10, 5, 10, 10);
        roundedPanel.add(jTextFieldUsuario, gbc);

        // Etiqueta de contraseña en la siguiente fila
        gbc.gridy = 2;
        gbc.gridx = 0;
        gbc.anchor = java.awt.GridBagConstraints.EAST;
        roundedPanel.add(jLabelPassword, gbc);

        // Campo de texto de contraseña al lado de la etiqueta
        gbc.gridx = 1;
        gbc.anchor = java.awt.GridBagConstraints.WEST;
        roundedPanel.add(jTextFieldPassword, gbc);

        // Botón de ingreso en la última fila, centrado
        gbc.gridy = 3;
        gbc.gridx = 0;
        gbc.gridwidth = 2; // Ocupa ambas columnas para centrarse
        gbc.anchor = java.awt.GridBagConstraints.CENTER;
        gbc.insets = new java.awt.Insets(20, 0, 10, 0);
        jButtonIngresar.setPreferredSize(new java.awt.Dimension(120, 40));
        roundedPanel.add(jButtonIngresar, gbc);

        // Ajuste del layout de jPanel1 para centrar el RoundedPanel
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(roundedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(roundedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        // Revalidar y repintar para actualizar la interfaz
        jPanel1.revalidate();
        jPanel1.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JPasswordField();
        jTextFieldUsuario = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 51, 255));
        setPreferredSize(new java.awt.Dimension(1200, 640));

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jButtonIngresar.setBackground(new java.awt.Color(51, 51, 255));
        jButtonIngresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(51, 255, 255));
        jButtonIngresar.setText("INGRESAR");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 0));
        jLabelUsuario.setText("USUARIO");

        jLabelPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 0));
        jLabelPassword.setText("PASSWORD");

        jTextFieldPassword.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldUsuario.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jButtonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        // TODO add your handling code here:
        // Obtener los valores ingresados
        String username = jTextFieldUsuario.getText();
        String password = new String(jTextFieldPassword.getPassword()); // Convertir el char[] a String

        // Crear una instancia de ConexionLogin y de Connection
        ConexionLogin conexionLogin = new ConexionLogin();
        Conexión conexion = new Conexión();
        Connection con = conexion.conectar();
    

        // Verificar las credenciales
        if(conexionLogin.esAdmin(username, password)){
            //Si es admin te mostrar el almacen, falta decorar el almacen
            cardLayout.show(principal.background, "almacen");
        }
        
        else if (conexionLogin.verificarUsuario(username, password, con,ID)) {
            
            cardLayout.show(principal.background, "tienda");
            
            //javax.swing.JOptionPane.showMessageDialog(this, "Ingreso exitoso!");
            // Lógica para avanzar en la aplicación o cambiar de pantalla
        }
        
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error de autenticación", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        // Cerrar la conexión
        try {
            if (con != null && !con.isClosed()) {
                con.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButtonIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
