package Vista;


import Controlador.ControladorVentas;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Ronnie Herrera
 */
public class Ventas extends javax.swing.JPanel { 
    private int IDCliente;
    private Connection con;

    // Constructor modificado para recibir los parámetros IDCliente y con
    public Ventas(/*int IDCliente, Connection con*/) {
        initComponents();
        /*this.IDCliente = IDCliente;
        this.con = con;*/
        // Instanciar el controlador con los parámetros
        //new ControladorVentas(this, IDCliente, con);
        
                
            MedioPago.add(jRadioButtonyape);
            MedioPago.add(jRadioButtonTranferencia);

            Comprobante.add(jRadioButtonFactura);
            Comprobante.add(jRadioButtonBoleta);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Comprobante = new javax.swing.ButtonGroup();
        MedioPago = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTotal = new javax.swing.JTextPane();
        jLabelTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        botonConfirmar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelTablaProductos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdCarrito = new javax.swing.JTable();
        jRadioButtonyape = new javax.swing.JRadioButton();
        jRadioButtonTranferencia = new javax.swing.JRadioButton();
        jLabelCorreo = new javax.swing.JLabel();
        jCheckBoxUsarMiCuenta = new javax.swing.JCheckBox();
        jLabelElijeComprobante = new javax.swing.JLabel();
        jRadioButtonFactura = new javax.swing.JRadioButton();
        jRadioButtonBoleta = new javax.swing.JRadioButton();
        jLabelMetodoPago = new javax.swing.JLabel();
        jCheckBoxTerminosCondiciones = new javax.swing.JCheckBox();
        botonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(95, 189, 214));
        setToolTipText("");

        jScrollPane2.setViewportView(txtTotal);

        jLabelTotal.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelTotal.setText("Total:");

        jPanel2.setBackground(new java.awt.Color(95, 189, 214));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(95, 189, 214));

        botonConfirmar.setBackground(new java.awt.Color(234, 121, 19));
        botonConfirmar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        botonConfirmar.setText("Confirmar ");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(botonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(botonConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(234, 121, 19));

        jLabelTablaProductos.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabelTablaProductos.setText("Resumen de compra");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tblProdCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Codigo", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblProdCarrito);

        jRadioButtonyape.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButtonyape.setText("Yape");
        jRadioButtonyape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonyapeActionPerformed(evt);
            }
        });

        jRadioButtonTranferencia.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButtonTranferencia.setText("Tranferencia ");

        jLabelCorreo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelCorreo.setText("Correo");

        jCheckBoxUsarMiCuenta.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jCheckBoxUsarMiCuenta.setText("Acepto usar mi informacion de cuenta para la reralización del pedido");
        jCheckBoxUsarMiCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUsarMiCuentaActionPerformed(evt);
            }
        });

        jLabelElijeComprobante.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelElijeComprobante.setText("Comprobante");

        jRadioButtonFactura.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButtonFactura.setText("Factura");
        jRadioButtonFactura.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jRadioButtonFacturaComponentHidden(evt);
            }
        });
        jRadioButtonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFacturaActionPerformed(evt);
            }
        });

        jRadioButtonBoleta.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jRadioButtonBoleta.setText("Boleta");
        jRadioButtonBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBoletaActionPerformed(evt);
            }
        });

        jLabelMetodoPago.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelMetodoPago.setText("Medio de pago");

        jCheckBoxTerminosCondiciones.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jCheckBoxTerminosCondiciones.setText("Aceptop los terminos y condiciones ");
        jCheckBoxTerminosCondiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTerminosCondicionesActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(234, 121, 19));
        botonCancelar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        botonCancelar.setText("Cancelar ");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gatoDinero.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxUsarMiCuenta)
                    .addComponent(jCheckBoxTerminosCondiciones)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelElijeComprobante)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jRadioButtonFactura))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jRadioButtonBoleta))
                                    .addComponent(jLabelMetodoPago)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jRadioButtonyape))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jRadioButtonTranferencia)))
                                .addGap(107, 107, 107)
                                .addComponent(jLabel1))
                            .addComponent(jLabelCorreo)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabelTotal)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelElijeComprobante)
                                .addGap(8, 8, 8)
                                .addComponent(jRadioButtonFactura)
                                .addGap(6, 6, 6)
                                .addComponent(jRadioButtonBoleta)
                                .addGap(14, 14, 14)
                                .addComponent(jLabelMetodoPago)
                                .addGap(14, 14, 14)
                                .addComponent(jRadioButtonyape)
                                .addGap(7, 7, 7)
                                .addComponent(jRadioButtonTranferencia))
                            .addComponent(jLabel1))
                        .addComponent(jLabelCorreo)
                        .addGap(4, 4, 4)
                        .addComponent(jCheckBoxUsarMiCuenta)
                        .addGap(8, 8, 8)
                        .addComponent(jCheckBoxTerminosCondiciones)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTotal)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonyapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonyapeActionPerformed
     
    }//GEN-LAST:event_jRadioButtonyapeActionPerformed

    private void jRadioButtonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFacturaActionPerformed
  
    }//GEN-LAST:event_jRadioButtonFacturaActionPerformed

    private void jRadioButtonFacturaComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jRadioButtonFacturaComponentHidden
    }//GEN-LAST:event_jRadioButtonFacturaComponentHidden

    private void jCheckBoxUsarMiCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUsarMiCuentaActionPerformed

    }//GEN-LAST:event_jCheckBoxUsarMiCuentaActionPerformed

    private void jCheckBoxTerminosCondicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTerminosCondicionesActionPerformed
 
    }//GEN-LAST:event_jCheckBoxTerminosCondicionesActionPerformed

    private void jRadioButtonBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBoletaActionPerformed
 
    }//GEN-LAST:event_jRadioButtonBoletaActionPerformed

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
    
    }//GEN-LAST:event_botonConfirmarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed

    }//GEN-LAST:event_botonCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup Comprobante;
    public javax.swing.ButtonGroup MedioPago;
    public javax.swing.JButton botonCancelar;
    public javax.swing.JButton botonConfirmar;
    public javax.swing.JCheckBox jCheckBoxTerminosCondiciones;
    public javax.swing.JCheckBox jCheckBoxUsarMiCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelElijeComprobante;
    private javax.swing.JLabel jLabelMetodoPago;
    private javax.swing.JLabel jLabelTablaProductos;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JRadioButton jRadioButtonBoleta;
    public javax.swing.JRadioButton jRadioButtonFactura;
    public javax.swing.JRadioButton jRadioButtonTranferencia;
    public javax.swing.JRadioButton jRadioButtonyape;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblProdCarrito;
    public javax.swing.JTextPane txtTotal;
    // End of variables declaration//GEN-END:variables

  
}
